# WhatATheme
markdown: kramdown

#Desabilitar
#kramdown:
 # syntax_highlighter_opts:
  #  disable: true

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Gmichet
# Description of the Site
description: Sitio personal de proyectos y blogs
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/Post/favicon/favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://freeimage.host/i/HrpHc0P
heroimage: https://iili.io/HyX595P.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: gabrielmichet@gmail.com
#facebook_username: thedevslot
twitter_username: Gmichet1
#instagram_username: thedevslot
linkedin_username: gabrielmichet
github_username:  Gmichet
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Gmichet

# Name of the Author
author-name: Gmichet
# URL for the Image of the Author
author-image: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgjAHwCs_2EV0O7te3b6p9LYPBaopOmrk9bcqULLkE4uOKUo6iig60O9prz9K3O6Dm20Fe7r4f67zU7JSHUa37ws-RiP5pc3jK9gNvneoGeDvMlj5C-eOOMt8X_uP88lHEmb8G8G69OT8MMT2SaQ6rfPL5X2k9QRfF_Syu8aJ0kRA-a/s220/Gmichet.png
# 60 Words About the Author
author-about: Autodidacta apasionado por la informática y entusiasta de los CTF. Constantemente aprendiendo.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Gmichet

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll/tagging

# Configuración de búsqueda
search_enabled: true
search_scope_options: [all, title, categories, tags]

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
